name: Build and Package C++ Project on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          # Update Homebrew and install required packages
          brew update
          brew install curl sqlite3 boost openssl cmake qt@6

          # Create QtIFW directory
          sudo mkdir -p "/opt/QtIFW/Contents/MacOS"
          
          # Download and extract QtIFW
          QTIFW_VERSION=4.8.1
          echo "Downloading QtIFW..."
          curl -L "https://download.qt.io/official_releases/qt-installer-framework/${QTIFW_VERSION}/QtInstallerFramework-macOS-x64-${QTIFW_VERSION}.tar.gz" -o qtifw.tar.gz
          
          echo "Extracting QtIFW..."
          tar xzf qtifw.tar.gz
          
          echo "Listing extracted contents:"
          ls -la
          
          # Copy the binaries to the correct location
          sudo cp -v ./QtInstallerFramework-macOS-x64-*/bin/* "/opt/QtIFW/Contents/MacOS/"
          
          # Set proper permissions
          sudo chmod -R 755 "/opt/QtIFW"
          
          # Verify binary installation
          echo "Verifying binary installation..."
          ls -la "/opt/QtIFW/Contents/MacOS"
          
          # Set environment variables
          echo "QTIFW_ROOT=/opt/QtIFW/Contents" >> $GITHUB_ENV
          echo "PATH=/opt/QtIFW/Contents/MacOS:$PATH" >> $GITHUB_ENV
          echo "Qt6_DIR=/opt/homebrew/opt/qt@6/lib/cmake/Qt6" >> $GITHUB_ENV

      - name: Verify Installation
        run: |
          echo "Current PATH: $PATH"
          echo "QTIFW_ROOT: $QTIFW_ROOT"
          echo "Contents of QtIFW directory:"
          ls -la "/opt/QtIFW/Contents/MacOS"
          
          echo "Testing binarycreator:"
          if [ -f "/opt/QtIFW/Contents/MacOS/binarycreator" ]; then
            echo "binarycreator exists"
            /opt/QtIFW/Contents/MacOS/binarycreator --version
          else
            echo "binarycreator not found!"
            exit 1
          fi

      - name: Create Build Directory
        run: mkdir build

      - name: Configure with CMake
        env:
          OPENSSL_ROOT_DIR: /opt/homebrew/opt/openssl
          CMAKE_PREFIX_PATH: /opt/homebrew/opt/qt@6
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                  -DCPACK_IFW_ROOT="/opt/QtIFW/Contents" \
                  -DCPACK_IFW_BINARYCREATOR_EXECUTABLE="/opt/QtIFW/Contents/MacOS/binarycreator" \
                  -DCPACK_GENERATOR="IFW" \
                  -DCMAKE_VERBOSE_MAKEFILE=ON

      - name: Build with Make
        run: |
          cd build
          make -j$(sysctl -n hw.ncpu) VERBOSE=1

      - name: Package with CPack
        run: |
          cd build
          echo "Using QTIFW_ROOT: $QTIFW_ROOT"
          echo "Checking binarycreator:"
          ls -la "/opt/QtIFW/Contents/MacOS/binarycreator"
          
          # Run CPack with verbose output
          VERBOSE=1 cpack -G IFW --debug \
                -D CPACK_VERBOSE=1 \
                -D CPACK_IFW_VERBOSE=1 \
                -D CPACK_IFW_ROOT="/opt/QtIFW/Contents" \
                -D CPACK_IFW_BINARYCREATOR_EXECUTABLE="/opt/QtIFW/Contents/MacOS/binarycreator"

      - name: Upload package artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: packaged-artifacts
          path: build/*.dmg