name: Build and Package C++ Project on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          # Update Homebrew and install required packages
          brew update
          brew install curl sqlite3 boost openssl cmake qt@6

          # Download Qt Installer Framework DMG
          QTIFW_VERSION=4.8.1
          curl -Lo qtifw.dmg https://download.qt.io/official_releases/qt-installer-framework/${QTIFW_VERSION}/QtInstallerFramework-macOS-x64-${QTIFW_VERSION}.dmg

          # Mount the DMG
          hdiutil attach qtifw.dmg

          # Create QtIFW directory
          sudo mkdir -p "/opt/QtIFW"
          
          # Copy Qt Installer Framework files (using sudo to avoid permission issues)
          sudo cp -R "/Volumes/QtInstallerFramework-macOS-x64-4.8.1/QtInstallerFramework-macOS-x64-4.8.1.app/Contents/MacOS/" "/opt/QtIFW/"
          
          # Set proper permissions
          sudo chmod -R 755 "/opt/QtIFW"
          
          # Unmount the DMG
          hdiutil detach "/Volumes/QtInstallerFramework-macOS-x64-4.8.1"

          # Set environment variables
          echo "QTIFW_ROOT=/opt/QtIFW" >> $GITHUB_ENV
          echo "PATH=/opt/QtIFW:$PATH" >> $GITHUB_ENV
          echo "Qt6_DIR=/opt/homebrew/opt/qt@6/lib/cmake/Qt6" >> $GITHUB_ENV

      - name: Verify Installation
        run: |
          echo "Current PATH: $PATH"
          echo "QTIFW_ROOT: $QTIFW_ROOT"
          echo "Checking QtIFW installation:"
          ls -la "/opt/QtIFW"
          echo "Testing binarycreator:"
          /opt/QtIFW/binarycreator --version || echo "binarycreator not found"

      - name: Create Build Directory
        run: mkdir build

      - name: Configure with CMake
        env:
          OPENSSL_ROOT_DIR: /opt/homebrew/opt/openssl
          CMAKE_PREFIX_PATH: /opt/homebrew/opt/qt@6
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                  -DCPACK_IFW_ROOT="/opt/QtIFW" \
                  -DCPACK_GENERATOR="IFW"

      - name: Build with Make
        run: |
          cd build
          make -j$(sysctl -n hw.ncpu)

      - name: Package with CPack
        run: |
          cd build
          echo "Using QTIFW_ROOT: $QTIFW_ROOT"
          cpack -G IFW -V

      - name: Upload package artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: packaged-artifacts
          path: build/*.dmg