name: Build and Package C++ Project on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          # Update Homebrew and install required packages
          brew update
          brew install curl sqlite3 boost openssl cmake qt@6
          brew tap jmuelbert/qtifw
          brew install qtifw
          echo "Qt6_DIR=/opt/homebrew/opt/qt@6/lib/cmake/Qt6" >> $GITHUB_ENV
          echo "CPACK_IFW_ROOT=${QTIFW_ROOT}" >> $GITHUB_ENV

      - name: Verify Installation
        shell: bash
        run: |
          echo "Current PATH: $PATH"
          echo "CPACK_IFW_ROOT: $CPACK_IFW_ROOT"
          echo "Checking QtIFW installation:"
          ls -la "$HOME/QtIFW/bin"
          echo "Checking binarycreator:"
          find "$HOME/QtIFW" -name "binarycreator"
          which binarycreator || echo "binarycreator not found in PATH"
          which cpack || echo "cpack not found in PATH"

      - name: Create Build Directory
        run: mkdir build

      - name: Configure with CMake
        env:
          OPENSSL_ROOT_DIR: /opt/homebrew/opt/openssl
          CMAKE_PREFIX_PATH: /opt/homebrew/opt/qt@6
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                   -DCPACK_IFW_ROOT="$CPACK_IFW_ROOT" \
                   -DCPACK_GENERATOR="IFW"

      - name: Build with Make
        run: |
          cd build
          make -j$(sysctl -n hw.ncpu)

      - name: Package with CPack
        run: |
          cd build
          cpack

      - name: Upload package artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: packaged-artifacts
          path: |
            build/*.dmg
            build/bin/phoenix.app
